/**
 * 문서 경로: `@/src/api/endpoints/code.ts`
 * 문서 제목: API 엔드포인트: code
 */

export const CODE = {
  ORGANIZATION_TYPES: '/api/codes/organization-types',
  ORGANIZATION_STATUSES: '/api/codes/organization-statuses',
  QUALIFIED_TYPES: '/api/codes/qualified-types',
  BRANCH_STATUSES: '/api/codes/branch-statuses',
  USER_ROLE_LEVELS: '/api/codes/user-role-levels',
  REGISTRY_TYPES: '/api/codes/registry-types',
  REGISTRY_CAUSES: '/api/codes/registry-causes',
  PARTY_TYPES: '/api/codes/party-types',
  PROPERTY_TYPES: '/api/codes/property-types',
  SECTIONS: '/api/codes/sections',
  REGISTRY_METHODS: '/api/codes/registry-methods',
  SECURED_DEBT_SCOPE_TYPES: '/api/codes/secured-debt-scope-types',
  CERTIFICATE_TYPES: '/api/codes/certificate-types',
  WORK_TYPES: '/api/codes/work-types',
  PAYMENT_STATUSES: '/api/codes/payment-statuses',
  ADMIN_INFO_LINK_TIMES: '/api/codes/admin-info-link-times',
  USER_STATUSES: '/api/codes/user-statuses',
  ASSIGNED_WORKS: '/api/codes/assigned-works',
  PROGRESS_STATUSES: '/api/codes/progress-statuses',
  QUOTE_PROGRESS_STATUSES: '/api/codes/quote-progress-statuses',
  ESTIMATE_WRITING_STATUSES: '/api/codes/estimate-writing-statuses',
  ESTIMATE_SELECTION_STATUSES: '/api/codes/estimate-selection-statuses',
  PROGRESS_TYPES: '/api/codes/progress-types',
  PARTY_ROLES: '/api/codes/party-roles',
  PARTY_ROLES_FOR_REQUEST: '/api/codes/party-roles-for-request',
  REGISTRY_TYPES_FOR_ASSIGN: '/api/codes/registry-types-for-assign',
  ACTION_TYPES: '/api/codes/action-types',
  BOND_PURCHASE_TYPES: '/api/codes/bond-purchase-types',
  CORRECTION_TYPES: '/api/codes/correction-types',
  DATA_SOURCES: '/api/codes/data-sources',
  E_SIGNATURE_METHODS: '/api/codes/e-signature-methods',
  E_SIGNATURE_STATUSES: '/api/codes/e-signature-statuses',
  FILE_PROGRESS_DOCUMENT_TYPES: '/api/codes/file-progress-document-types',
  FILE_REGISTRY_TYPES: '/api/codes/file-registry-types',
  FILE_REQUEST_DOCUMENT_TYPES: '/api/codes/file-request-document-types',
  OWNERSHIP_TYPES: '/api/codes/ownership-types',
  PROCESS_ACTIONS: '/api/codes/process-actions',
  PROPERTY_BUILD_TYPES: '/api/codes/property-build-types',
  RPA_USER_TASK_STATUSES: '/api/codes/rpa-user-task-statuses',
  RPA_USER_TASK_TYPES: '/api/codes/rpa-user-task-types',
  CONFIRMATION_DOCUMENT_TYPES: '/api/codes/confirmation-document-types',
  FILE_BRANCH_DOCUMENT_TYPES: '/api/codes/file-branch-document-types',
  SUCCESS_CODES: '/api/codes/success-codes',
  ERROR_CODES: '/api/codes/error-codes',
  WORKFLOW_NOTIFICATION_EVENT: '/api/codes/workflow-notification-event',
  NOTICE_CATEGORY: '/api/codes/notice-category'
} as const
