/**
 * 문서 경로: `@/src/api/endpoints/index.ts`
 * 문서 제목: index 구현 파일
 */

import { ADDRESS } from '@/api/endpoints/address'
import { AUTH } from '@/api/endpoints/auth'
import { BANK } from '@/api/endpoints/bank'
import {
  BRANCH,
  BRANCH_BANK,
  BRANCH_DOCUMENT,
  BRANCH_PAYMENT,
  BRANCH_PREPAID,
  BRANCH_REGISTRY
} from '@/api/endpoints/branch'
import { CODE } from '@/api/endpoints/code'
import { CRYPTO } from '@/api/endpoints/crypto'
import { NOTICE } from '@/api/endpoints/notice'
import { NOTIFICATION } from '@/api/endpoints/notification'
import { ORGANIZATION } from '@/api/endpoints/organization'
import {
  REGISTRY_ADMIN_CONSENT,
  REGISTRY_ATTACHMENT,
  REGISTRY_CANCELLATION,
  REGISTRY_CASE,
  REGISTRY_CERTIFICATE,
  REGISTRY_CHANGE,
  REGISTRY_COMPLETION,
  REGISTRY_CONTRACT,
  REGISTRY_CORRECTION,
  REGISTRY_DASHBOARD,
  REGISTRY_DEBT_TAX,
  REGISTRY_HOUSING_BOND,
  REGISTRY_LOAN_ACCOUNT,
  REGISTRY_PRIOR_LOAN,
  REGISTRY_PROGRESS,
  REGISTRY_PROGRESS_DOCUMENT,
  REGISTRY_PROPERTY,
  REGISTRY_QUOTE,
  REGISTRY_RECEIPT,
  REGISTRY_RECEIPT_DOCUMENT,
  REGISTRY_REQUEST_DOCUMENT,
  REGISTRY_SCHEDULE,
  REGISTRY_SIGNATURE,
  REGISTRY_TAX,
  REGISTRY_TAX_REPORT,
  REGISTRY_TEST,
  REGISTRY_TRANSFER_CERTIFICATE,
  REGISTRY_TYPE
} from '@/api/endpoints/registry'
import { RPA } from '@/api/endpoints/rpa'
import { USER } from '@/api/endpoints/user'

export const API = {
  ADDRESS,
  ORGANIZATION,
  BRANCH,
  BRANCH_BANK,
  BRANCH_PAYMENT,
  BRANCH_REGISTRY,
  BRANCH_PREPAID,
  BRANCH_DOCUMENT,
  USER,
  AUTH,
  BANK,
  CODE,
  NOTIFICATION,
  NOTICE,
  REGISTRY_TEST,
  REGISTRY_REQUEST_DOCUMENT,
  REGISTRY_QUOTE,
  REGISTRY_DASHBOARD,
  REGISTRY_PROGRESS,
  REGISTRY_PRIOR_LOAN,
  REGISTRY_TYPE,
  REGISTRY_CONTRACT,
  REGISTRY_PROPERTY,
  REGISTRY_CERTIFICATE,
  REGISTRY_DEBT_TAX,
  REGISTRY_TAX,
  REGISTRY_ATTACHMENT,
  REGISTRY_CHANGE,
  REGISTRY_CORRECTION,
  REGISTRY_CANCELLATION,
  REGISTRY_ADMIN_CONSENT,
  REGISTRY_SIGNATURE,
  REGISTRY_TAX_REPORT,
  REGISTRY_HOUSING_BOND,
  REGISTRY_LOAN_ACCOUNT,
  REGISTRY_TRANSFER_CERTIFICATE,
  REGISTRY_CASE,
  REGISTRY_RECEIPT,
  REGISTRY_RECEIPT_DOCUMENT,
  REGISTRY_COMPLETION,
  REGISTRY_PROGRESS_DOCUMENT,
  REGISTRY_SCHEDULE,
  RPA,
  CRYPTO
} as const
